HS_DOMAIN=matrix.company.local
ELEMENT_DOMAIN=chat.company.local
BASE_DOMAIN=company.local
PUBLIC_IP=192.168.1.100
LE_EMAIL=admin@company.local
SSL_MODE=selfsigned
PG_DB=synapse
PG_USER=synapse_user
PG_HOST=localhost
PG_PORT=5432
